title: ctrlyzza's Data Science Portfolio
#logo: assets/img/headshot_circle.png
description: **CPA | Graphic Designer | Data Enthusiast** 🌱 <br> I strive to build a multi-disciplinary life. Currently on a journey to learn more programming languages!
show_downloads: true
theme: jekyll-theme-minimal
